spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql.init.mode: always

logging:
  level:
    org.springframework.web: INFO
server:
  error:
    include-exception: false
    include-message: always
    include-stacktrace: never
---
logging:
  level:
    org.springframework.web: DEBUG

spring:
  config:
    activate:
      on-profile: test
  security:
    user:
      name: user
      password: 123
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 20

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql.init.mode: always
